final

diff --git a/bin/dsvc b/bin/dsvc
--- a/bin/dsvc
+++ b/bin/dsvc
@@ -60,22 +60,19 @@ fi
 name=$1;
 action=$2;
 
+if [ ! -d $HOME/etc/dsvc.d/$name ]; then
+    echo "Directory[$HOME/etc/dsvc.d/$name ] dones not exist" | color red bold;
+    exit 0;
+fi
+
 #
 # 读取配置文件
 #
-if [ ! -f $HOME/etc/dsvc.d/$name ]; then
-    echo "File[$HOME/etc/dsvc.d/$name] does not exist" | color red bold;
+if [ ! -f $HOME/etc/dsvc.d/$name/${name}.main ]; then
+    echo "File[$HOME/etc/dsvc.d/${name}.main] does not exist" | color red bold;
     exit 0;
 fi
-source $HOME/etc/dsvc.d/$name
-
-# 容器的config脚本, 用于ssh进入容器配置
-if [ -f $HOME/etc/dsvc.d/${name}.config ]; then
-    config=`cat $HOME/etc/dsvc.d/${name}.config`
-else
-    config='echo "no config needed';
-fi
-
+source $HOME/etc/dsvc.d/$name/${name}.main
 
 # 检查服务配置 - image
 if [ ! $image ]; then
@@ -103,8 +100,8 @@ fi
 function run {
     # 创建并启动容器
     echo "1. create and start a container..." | color green bold;
-    if [ -f $HOME/etc/dsvc.d/$name.option ]; then
-        option=$(cat $HOME/etc/dsvc.d/$name.option| perl -pe 's/\n/ /g');
+    if [ -f $HOME/etc/dsvc.d/$name/$name.option ]; then
+        option=$(cat $HOME/etc/dsvc.d/$name/$name.option| perl -pe 's/\n/ /g');
     fi
 
     # msg=$(docker run -it -d --name $name --hostname $name "$option" $image:$version 2>&1); errno=$?;
@@ -129,16 +126,17 @@ function run {
 
     # 3. ssh进入容器配置
     echo "3. ssh into container[$name]  and config it..." | color green bold;
-    cmd="scp $HOME/etc/dsvc.d/$name.config root@$ip:/dsvc-config.sh";
-    # echo "cmd=[$cmd]";
-    msg=$($cmd);
-      
-    cmd="ssh root@$ip bash /dsvc-config.sh"
-    # echo "cmd[$cmd]"
-    msg=$($cmd); errno=$?;
-    if  [  $errno -ne 0 ] ; then 
+    if [ -f $HOME/etc/dsvc.d/$name/$name.config ]; then
+        cmd="scp $HOME/etc/dsvc.d/$name.config root@$ip:/dsvc-config.sh";
+        # echo "cmd=[$cmd]";
+        msg=$($cmd);
+        cmd="ssh root@$ip bash /dsvc-config.sh"
+        # echo "cmd[$cmd]"
+        msg=$($cmd); errno=$?;
+        if  [  $errno -ne 0 ] ; then 
         echo "failed msg[$msg]" | color red bold;
-        exit 0;
+            exit 0;
+        fi
     fi
 
     # 启动容器内服务
@@ -171,11 +169,13 @@ function start {
 
     # 3. ssh进入容器配置
     echo "3. if needed, ssh into container[$name]  and config it..." | color green bold;
-    cmd="ssh root@$ip bash /dsvc-config.sh"
-    msg=$($cmd); errno=$?;
-    if  [  $errno -ne 0 ] ; then 
-        echo "failed msg[$msg]" | color red bold;
-        exit 0;
+    if [ -f $HOME/etc/dsvc.d/$name/$name.config ]; then
+        cmd="ssh root@$ip bash /dsvc-config.sh"
+        msg=$($cmd); errno=$?;
+        if  [  $errno -ne 0 ] ; then 
+            echo "failed msg[$msg]" | color red bold;
+            exit 0;
+        fi
     fi
 
     # 4. 在容器内exec服务
