支持多IP设置

diff --git a/bin/dsvc b/bin/dsvc
--- a/bin/dsvc
+++ b/bin/dsvc
@@ -112,26 +112,32 @@ function run {
 
     # 设置IP地址
     echo  "2. set ip address for container[$name]..." | color green bold;
-    cmd="ssh root $pipework br-${USER} $name $ip/$mask@$gateway 2>&1";
-    # echo "cmd: [$cmd]";
-    msg=$($cmd); errno=$?;
-    if  [  $errno -ne 0 ] ; then 
-        echo "failed msg[$msg]" | color red bold;
-        exit 0;
-    fi
+    eid=0;
+    for ipk in `echo $ip | sed 's/,/\n/'`; do 
+        cmd="ssh root $pipework br-${USER} -i enc$eid $name $ipk/$mask@$gateway 2>&1"; # echo "cmd: [$cmd]";
+        msg=$($cmd); errno=$?;
+        if  [  $errno -ne 0 ] ; then 
+            echo "failed msg[$msg]" | color red bold;
+            exit 0;
+        fi
+        if [ "x$ipc" = "x" ]; then
+            ipc=$ipk
+        fi
+        ((eid=eid+1))
+    done 
 
     # 3. ssh进入容器配置
     echo "3. ssh into container[$name]  and config it..." | color green bold;
-    cmd="scp $HOME/etc/dsvc.d/$name/$name.config root@$ip:/dsvc-config.sh"; # echo "cmd=[$cmd]";
+    cmd="scp $HOME/etc/dsvc.d/$name/$name.config root@$ipc:/dsvc-config.sh"; # echo "cmd=[$cmd]";
     msg=$($cmd);
 
-    cmd="scp $HOME/etc/dsvc.d/$name/$name.run    root@$ip:/dsvc-run.sh";    # echo "cmd=[$cmd]";
+    cmd="scp $HOME/etc/dsvc.d/$name/$name.run    root@$ipc:/dsvc-run.sh";    # echo "cmd=[$cmd]";
     msg=$($cmd);
 
-    cmd="ssh root@$ip chmod +x /dsvc-*.sh" # echo "cmd[$cmd]"
+    cmd="ssh root@$ipc chmod +x /dsvc-*.sh" # echo "cmd[$cmd]"
     msg=$($cmd); errno=$?;
 
-    cmd="ssh root@$ip /dsvc-config.sh" # echo "cmd[$cmd]"
+    cmd="ssh root@$ipc /dsvc-config.sh" # echo "cmd[$cmd]"
     msg=$($cmd); errno=$?;
     if  [  $errno -ne 0 ] ; then 
         echo "failed msg[$msg]" | color red bold;
@@ -140,7 +146,7 @@ function run {
 
     # 启动容器内服务
     echo "4. start service..." | color green bold;
-    cmd="ssh root@$ip nohup /dsvc-run.sh start";  # echo "cmd[$cmd]";
+    cmd="ssh root@$ipc nohup /dsvc-run.sh start";  # echo "cmd[$cmd]";
     msg=$($cmd); errno=$?;
     if  [  $errno -ne 0 ] ; then 
         echo "failed msg[$msg]" | color red bold;
@@ -159,15 +165,21 @@ function start {
 
     # 2. 设置容器IP
     echo "2. set ip address for container[$name]..." | color green bold;
-    msg=$(ssh root $pipework $br $name $ip/$mask@$gateway 2>&1); errno=$?;
-    if  [  $errno -ne 0 ] ; then 
-        echo "failed msg[$msg]" | color red bold;
-        exit 0;
-    fi
+    for ipk in `echo $ip | sed 's/,/\n/'`; do
+        cmd="ssh root $pipework br-${USER} $name $ipk/$mask@$gateway 2>&1"; # echo "cmd: [$cmd]";
+        msg=$($cmd); errno=$?;
+        if  [  $errno -ne 0 ] ; then
+            echo "failed msg[$msg]" | color red bold;
+            exit 0;
+        fi
+        if [ "x$ipc" = "x" ]; then
+            ipc=$ipk
+        fi
+    done
 
     # 3. ssh进入容器配置
     echo "3. if needed, ssh into container[$name]  and config it..." | color green bold;
-    cmd="ssh root@$ip /dsvc-config.sh";  # echo "cmd[$cmd]";
+    cmd="ssh root@$ipc /dsvc-config.sh";  # echo "cmd[$cmd]";
     msg=$($cmd); errno=$?;
     if  [  $errno -ne 0 ] ; then 
         echo "failed msg[$msg]" | color red bold;
@@ -176,7 +188,7 @@ function start {
 
     # 4. 在容器内exec服务
     echo "4. start service..." | color green bold;
-    cmd="ssh root@$ip nohup /dsvc-run.sh start"; # echo "cmd[$cmd]";
+    cmd="ssh root@$ipc nohup /dsvc-run.sh start"; # echo "cmd[$cmd]";
     msg=$($cmd); errno=$?;
     if  [  $errno -ne 0 ] ; then 
         echo "failed msg[$msg]" | color red bold;
